atom/language-go

grammars/go.cson
spec/go-spec.coffee

Built-in function keywords weren't being properly detected because they were below the `functions` object. 
Also added support for these keywords' arguments to be named as `storage.type.go`.

Fix grammer of built-in functions and their data types

---

grammars/go.cson
spec/go-spec.coffee

This time exactly according to the Go language specs.... As for the details, again the same two screenshots (the print verbs changes are according to the specs but the escaped chars part wasn't so removed that part). 
Before:
After:

Add print verbs recognition in raw quotes and fix rune (single quote string) recognition

---

settings/language-go.cson

I know at least two [1][2] corner cases which are still not 100% after adding this fix. But those corner cases require a tweak to Atom itself. This has to do with the need for an option to decrease the indent level
based on the previous line, which currently is not supported in Atom.
Take this use case:
```
s := fmt.Sprint(“some” +
“thing”)
fmt.Print(s)
```
[1] The indentation for this is now done correctly for the first line, but only if you press enter after the `+` sign while the statement is already complete (so `"thing")` is on the same line already. But if you type this in (which is of course expected behaviour) and while typing you hit enter right after the `+` sign with only a `)` behind the cursor, it will not indent.
This is correct as a single `)` on a line is closing an …

Fixes #31 and #41

---

settings/language-go.cson

As discussed earlier in PR #43, we need to extend the current options Atom has to determine what the correct indent level should be.
For this I created PR https://github.com/atom/atom/pull/6808 but in order to be able to write a proper test, I need at least one language package to include the new regexp so I can call it in the test.
So this is a little like the chicken and the egg. This new regexp will not currently be used by anything else than the tests and depending on the outcome of that PR it could need a refactor and or name change. But without adding this now and updating the version number in Atom for this package, I will not be able to finish the tests needed to get that PR merged.
So it would be very nice if we can merge this and cut a new release on it. Note that this will …

Adding new regexp to improve indentations

---

settings/language-go.cson

After having quite some discussions and improvements it seems we are now in the final stages of getting
https://github.com/atom/atom/pull/6808 merged.
One thing remaining is that we decided to revert some names and update this name. So it would be really nice if we can get this one merged and released asap, so I can make the final update to https://github.com/atom/atom/pull/6808 in order to let @maxbrunsfeld press the big green button :wink:

Updated the name to be more inline with TextMate

---

snippets/language-go.cson

Adding a snippet for printf with "%+v" for printing out non-strings. The snippet is:
'body': "fmt.Printf(\"$1  %+v \\\\n\", ${1:e})$0"
Which translates to:
fmt.Printf("someVar  %+v \n", someVar)

added snipppet "fmt printf" for printing via %+v

---

snippets/language-go.cson

None of the prefixes changed except for 1, so all other snippets are still called by the same prefix they currently have.
The `Im` prefix (used for adding a multi import snippet) is changed to `ims`. This seems to make more sense and is easier/faster to type as you no longer have to use the additional `shift` key and `im` is for calling the single import snippet.
So what changed is that mainly the descriptions are updated so they better explain/describe the snippet and the body is (where possible and logical) generalised a bit.

Generalising and tweaking snippets

---

grammars/go.cson
spec/go-spec.coffee

This makes the `language-go` more inline with the other language packages.
Thanks @Victorystick for pointing this out!

Update the scope used for function declarations

---

grammars/go.cson

By making the matching more precise (and so more correct) as @joefitzgerald suggested.
The test where already testing this correctly, so the fact that they still pass proves this has no negative impact.

Fixes issue #33

---

grammars/go.cson
spec/go-spec.coffee

This way the ordering doesn’t matter, they will be matched correctly without overlapping with other matches.
And also renamed the `constant.escape.format-verb.go` to `constant.character.escape.go` to be consistent with other language packages enabling better highlighting.

Improving the regexps for the delimiters

---

grammars/go.cson
spec/go-spec.coffee

- Improve scope names used
- Improve regexps to better match according to the language specs
- Prevent that everything that is not matched, is matched as a variable
- Update and fix existing tests (some turned out to be broken even before I started with this refactor, causing them to always return success while they actually failed)
- Add more tests
Even through functions are still scoped as `keyword.function.go` and not as `storage.type.function.go`, this PR still fixes issue #62 IMO. I've looked again and again at the language specs and also at other existing syntax highlighting packages for Go, and they all (Sublime, Emacs, Vim) seem to threat these (`chan`, `const`, `func`, `interface`, `map`, `struct`, `type` and `var`) as `keywords` instead of `support.types` that are used for these …

Refactor scoping to better match the TextMate guidelines

---

grammars/go.cson
spec/go-spec.coffee

This fixes unexpected highlighting where .variable and/or .constant are used in themes for specific highlights.

Fix scopes for variables and constants so they are highlighted correctly

---

spec/go-spec.coffee

This test makes sure the last changes (v0.40.0) are also working for some more complex variable assignments and/or initialisations.

Add an additional test

---

settings/language-go.cson
spec/language-go-spec.coffee

The capturing group m: `(?<m>[^()]*\\((?:\\g<m>|[^()]*)\\)[^()]*)`
is prone to catastrophic backtracking because the two [^()]* outside the
parentheses literals can both match each link in a chain a()b()c()d()...
Moving the latter [^()]* inside the parentheses has the same matching
behavior as the original regex and won't catastrophically backtrack.
Fixes https://github.com/atom/language-go/issues/78 and https://github.com/atom/atom/issues/10272.

decreaseNextIndentPattern: prevent catastrophic backtracking

---

snippets/language-go.cson

This adds a snippet for quickly writing context-aware http Handlers.
Depends on: golang.org/x/net/context

Add Snippet to handle Context, ResponseWriter, *http.Request handlers

---

grammars/go.cson
spec/go-spec.coffee

This adds two new scopes:
* `entity.alias.import.go`
* `entity.name.import.go`
This allows import declarations to be tokenized, and prevents them from being recognized as quoted strings. This paves the way for package autocompletion for single and multi-line import declarations:
`import "fmt"`
`import aliasedfmt "fmt"`
```
import (
"fmt"
)
```
```
import (
aliasedfmt "fmt"
)
```
Fixes https://github.com/joefitzgerald/go-plus/issues/226
Requires https://github.com/joefitzgerald/autocomplete-go/pull/50 to allow autocompletion in import statements

Add Scope For Alias and Package Name of Import Declarations

---

grammars/go.cson
spec/go-spec.coffee

Fixes comments not being recognized in multiline imports.
No alternate designs were considered.
Comments will be correctly highlighted in import regions, as expected.
None.
Fixes #102 
@joefitzgerald I have no idea how specs work in language-go so feel free to move the one I added to the import section if needed.

Fix comments in imports

---

settings/language-go.cson
spec/language-go-spec.coffee

Pretty self-explanatory.  If an opening bracket exists without any closing brackets, we should probably indent.  The `decreaseIndentPattern` change is purely cosmetic.
None.
Improved auto-indentation.
There hopefully should be none.
Fixes #87

Don't require a word before an opening bracket when indenting

---

grammars/go.cson
spec/go-spec.coffee

* Move all variable matches into #variables
* Prevent unnecessary tokenization (end at the equals sign)
* Fix assignments to existing variables
* Consolidate two existing variable matches into one
* Add support for multidimensional arrays with optional lengths
* Add examples
Prior to this PR, the variable matching rules would attempt to match all the way to the end of the line.  This is undesirable, because all it did was return control to `$self`.  However, since the rule was a simple `match`, this meant anything multiline would stop highlighting after …

Consolidate and improve variable matching

---

grammars/go.cson
spec/go-spec.coffee

Instead of checking to make sure that the first letter of a variable is part of the US alphabet, check instead that it is a word character and NOT a number.  This is primarily for non-ASCII variables.
/cc @pchaigno, @Alhadis: In the event that language-go is used to highlight Go code on GitHub in the future, I want to make sure that this syntax will be recognized by the engine that GitHub uses.
/cc @esdoppio: I saw that an alternative was `\p{L}`.  In the event that both are recognized, which would you prefer?  I know in the past that you've been using …

Tokenize variables starting with a non-ASCII letter

---

grammars/go.cson
spec/go-spec.coffee

Following #111, this PR removes the usage of positive lookbehinds from the remaining three keywords that use them: package, import, and type.  The main reason for doing so is because lookbehinds cannot be variable-width; this means that issues like #91 happen quite easily.  In addition, now that the keywords are tokenized alongside the content, it makes the patterns more readable and also allows a refactoring of the import patterns (similar to the variable refactor).
#116 was considered, but that adds more complexity to the lookbehind.  In comparison, …

Remove usage of lookbehinds

---

grammars/go.cson
spec/go-spec.coffee

Periods in Go, like in many other languages, act as qualifiers.  Allow them in variable declarations and assignments.  Also, support variadic array lengths.
None.
Any variable declaration containing qualified names or types or variadic array lengths should be tokenized correctly.
Regexes got a bit uglier.
Fixes #120
Fixes #121
Fixes #123
/cc @joefitzgerald

Periods are ok in variable declarations

---

grammars/go.cson
spec/go-spec.coffee

Instead of tokenizing the entire string as a constant, add the standard string scopes and only tokenize the character _inside_ of the string as a rune constant.  Some improper escapes have also been removed, and `\p{Any}` has been changed to `.` (which seems to be the same thing).
None.
Runes will receive proper string highlighting.
None.
Fixes #129

Add string scopes to runes

---

grammars/go.cson
spec/go-spec.coffee

Use recursive begin/end matching for curly and round brackets.
None.
Makes language-go consistent with most other languages, such as language-javascript, -java, -php, etc.
The brackets may be closed improperly if a rule matches an opening bracket but not a closing one.
Fixes #130

Use begin/end for brackets

---

grammars/go.cson
spec/go-spec.coffee

Changes the optional match for accessors to a multiple match, and changes the non-capturing group to an atomic group to avoid potential catastrophic backtracking.
Fixes #135

Support deeply nested variable names

---

grammars/go.cson
spec/go-spec.coffee

The regex to match `keyword.operator.comparison.go`
`(==|!=|<=|>=|<[^<]|>[^>])`
contains a mistake introduced to avoid matching the bitshift operators. `[^<]` and `[^>]` will match anything following the first less/greater than symbol (this highlights <3 and >3 and is even more obvious with `<3.0` or `>2.0 `
The correct regex is
`(==|!=|<=|>=|<(?!<)|>(?!>))`
as it uses negative lookaheads to avoid highlighting characters immediately following the less/greater than symbol.
If the negative lookahead is considered to be too greedy, the regex catching the …

Update keyword.operator.comparison.go regex

---

grammars/tree-sitter-go.cson
package.json

⚠️  Work In Progress ⚠️ 
This adds alternative grammars that uses [tree-sitter-go](https://github.com/tree-sitter/tree-sitter-go) for parsing instead of [first-mate](https://github.com/atom/first-mate).

Add tree-sitter parser

---

grammars/tree-sitter-go.cson

Fixes https://github.com/atom/language-go/issues/163 by adding fold rules for switch, select and case.
N/A
Can fold select switch and case
Someone wants to be unable to fold these things
Fixes https://github.com/atom/language-go/issues/163
/cc: @maxbrunsfeld

Fold select, switch, case

---

grammars/gomod.cson
grammars/gosum.cson

In Go 1.11 a new language feature was added called `modules`. These exist to support removing `$GOPATH`, encourage repeatable builds and semantic versioning your Go packages.  If you want to dig further into what they are, I think the Go team did a great job in their [documentation](https://golang.org/cmd/go/#hdr-Modules__module_versions__and_more) and in the community [wiki](https://github.com/golang/go/wiki/Modules).
This particular change to the Atom `language-go` package is to add the two new file types that `modules` introduced. 
Those files are:
- A checksum file (which has an extension of `.sum`) 
- A module file (which has an extension of `.mod`)
No particular alternatives stood out. 
When viewing module and checksum files the version numbers will be highlighted along with the …

Add support for Go module and checksum files

---

package-lock.json
package.json

`^version` means install any version that is compatible with the range.
This means npm can even install tree-sitter-javascript version 0.15
since in semver 0.15 should be compatible with 0.19. tree-sitter seems
to have broken semver. 0.15 is not compatible with 0.19

Install the exact version instead of range
